service: kubernetes-docs-language-labeler

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  profile: zparnold
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource:
        Fn::GetAtt:
          - PRQ
          - Arn
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:sqs:${self:provider.region}:'
            - Ref: AWS::AccountId
            - ':*'

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ingress:
    handler: bin/ingress
    events:
      - http:
          path: v1/webhook
          method: post
    environment:
        SQS_QUEUE_URL:
          Ref: PRQ
        GH_TOKEN: AQICAHizIzARq0uEDETKhyxhn1/4iwwtjfIVgYzwASSYtUxftAEwG/xsg9DABm1+CQgnGQzgAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDII6fkgQXAEEiFa4JgIBEIBDv5xE8Qt3i/BARgkEd4m8is4Vvqr0hGu4s9Gsqh9PdyiCZVkMqum3dpsixuxKy93EWW0rtbV0GCZ9l6HeKD7nCmSfiA==
        GH_ORG: zparnold
        GH_REPO: website
  runner:
    handler: bin/processor
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PRQ
              - Arn
          batchSize: 1

resources:
  Resources:
    PRQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PRQ"